//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace findmytutor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class city
    {
        public string city_name { get; set; }
        public int city_Id { get; set; }
        public int state_id { get; set; }
    }
}
